services:
  - type: web
    name: studyhive-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "5000"
      - key: BCRYPT_ROUNDS
        value: "10"

  - type: web
    name: studyhive-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
